name: Daily Internship Check

on:
  schedule:
    - cron: '0 8 * * *'   # Runs every day at 08:00 UTC (10:00 in Germany during summer)
  workflow_dispatch:       # Allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repo
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run script
      - name: Run internship checker
        run: python check_internships.py

      # 5. Download PDF files
      - name: Download PDF files
        run: python download_pdf.py

      # 6. Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add published_internships.txt downloads/
          git commit -m "Update internship list and PDFs [skip ci]" || echo "No changes to commit"
          git push
